### PR TITLE
Compiler fixes related to js.swc

### PR DESCRIPTION
**Pull request by adufilie**

### CODE REVIEW

**Comment by aharui** [comment]
Where was the toString() missing?   That change seems to be breaking the CreateJS externs build.  The classes generated from the externs generally don't include methods that are overridden from a base class, so the original code should have allowed a toString() in Object than needed to allow Number, int and uint to have custom toString() methods.

With your change, other classes are now being given toString() methods which is unexpected and fails.

**Comment by adufilie** [comment]
toString() was missing in every class except Number, int, uint.  I've found the problem and will add another commit here shortly.  Sorry about that.

**Comment by aharui** [comment]
Wasn't toString() on Object?  Then it doesn't need to exist on most other objects.  But we do need to allow Number, int and uint to have their own toString() with different parameters.

**Comment by adufilie** [comment]
Object.prototype.toString() is included in the es3.js extern file, but it has a different signature than Number.prototype.toString(opt_radix), so you cannot have it defined in Object.as and override in Number.as or any other file.  The original code had it working for Number/int/uint, but "new Date().toString()" was giving an error because it was not including the toString() function in the Date class.  "new Object().toString()" does not giving an error because Object uses the 'dynamic' keyword on the class definition.

One of the problems in createjs was that Filter.js documented toString() with @return {string} but ColorFilter (extends Filter) did not include a return type, so it became a void function and an incompatible override.  The other issue was that there was a hard-coded thing in MethodReference.java to output an "AS3" namespace for a toString() override.

**Comment by aharui** [comment]
Also, with the getStaticField/getInstanceField changes, 5 files of unit tests have compile errors.  They are: TestAnnotationEnum, TestConstructor, TestExternChrome, TestTypeExternals, TestTypeInheritance.

Can you fix those up as well?

Thanks

**Comment by joshtynjala** [comment]
> The other issue was that there was a hard-coded thing in MethodReference.java to output an "AS3" namespace for a toString() override.

Using the AS3 namespace for toString() is the correct behavior. It allows subclasses to reimplement the method without the override keyword.

In fact, if you look at the [API Reference](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Object.html#hasOwnProperty%28%29), you'll see that all methods defined on Object are in the AS3 namespace rather than public.

**Comment by joshtynjala** [comment]
Hmmm... strangely, toString() is not marked with the AS3 namespace in the API reference. However, if I recall correctly, it is AS3 instead of public in the playerglobal.swc. I'll double-check.

**Comment by joshtynjala** [comment]
Okay, it appears that Number and other classes with custom toString() methods put it in the AS3 namespace. You can see that with [Number.toString() in the API reference](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Number.html#toString%28%29) and it's the same in playerglobal.swc. For some reason, I thought it was the other way around. Regardless, ActionScript uses the AS3 namespace to avoid conflicts in toString() and some other methods because, as Alex noted, ActionScript is stricter than JavaScript.

**Comment by aharui** [comment]
I'm pretty sure it is that way so your subclasses of Object can override toString() although they can't add parameters to toString().

**Comment by adufilie** [comment]
Before the changes related to toString(), new Date().toString() was giving an error because the toString() function was missing from the generated Date.as.

When I include a toString() jn Object.as, I get a new error which does not normally occur in when compiling ActionScript:
    Incorrect number of arguments.  Expected no more than 0
        var test:* = (b2 & 0xF).toString(2);

I can define a toString() in a new class without using "override."  In fact, when I use "override" it's a compile error.  It does allow me to add parameters to my own toString().

**Comment by aharui** [comment]
I think where we want to end up is that Number, int and uint have toString(radix) in the AS3 namespace, and Date, Array, etc have toString().  The code may have to check that the super class is Object and not some subclass of Object and then emit the toString().  We may need to have Object's toString() be in the AS3 namespace as well, or just omit it and automatically add it to every class that extends Object directly.

You are right that Object.toString() does not allow the override keyword.  I'm not sure why that is but it is mentioned in the AS3 Language Reference.

**Comment by adufilie** [comment]
This is outputting ActionScript code to correspond to the JavaScript APIs, so I don't think the requirement of an AS3 namespace on Number.prototype.toString() etc. is necessary. I would argue that it is better to have less special-case code in the compiler.  The patched code outputs toString() in all the generated AS files where it appears in the JS externs except Object.as, where before it only appeared in Number/int/uint.

**Comment by adufilie** [comment]
I believe the patched code does the right thing. From the AS3 language reference:

>Note: Methods of the Object class are dynamically created on Object's prototype. To redefine this method in a subclass of Object, do not use the override keyword. For example, a subclass of Object implements function toString():String instead of using an override of the base class.

Therefore, the generated Object.as should not define toString().

Also, here's the description of the AS3 namespace:

>Defines methods and properties of the core ActionScript classes that are fixed properties instead of prototype properties. When you set the "-as3" compiler option to true (which is the default setting in Flex Builder 2), the AS3 namespace is automatically opened for all the core classes. This means that an instance of a core class will use fixed properties and methods instead of the versions of those same properties and methods that are attached to the class's prototype object. The use of fixed properties usually provides better performance, but at the cost of backward compatibility with the ECMAScript edition 3 language specification (ECMA-262).

It's a specific feature about gaining performance in Flash Player, and should not be a part of js.swc, which is meant to be an API for JavaScript.

**Comment by teotigraphix** [comment]
On a side note; When i wrote this externc, I had the same opinion as @adufilie. It was about getting the javascript out of valid AS, that was it.

The externc compiler was in my view an "interpreter" that could bend rules and make things work.

**Comment by joshtynjala** [comment]
I guess, since Object is dynamic, calling toString() should still compile if you try to call it on something typed as Object (even if it's not defined). That isn't ideal, since IDEs probably won't provide toString() as a code hint (and some might even show an error in the editor). If there's no compiler error, through, it seems like a workaround that we can live with.

**Comment by adufilie** [comment]
Flash Builder does not show toString() in its content assist for Object, and there is no error in the editor. =)

**Comment by joshtynjala** [comment]
Yes, I see that too. Weird.

**Comment by aharui** [comment]
What happens for some non-dynamic class that extends Object?  Does it get a toString() even if it doesn't define a custom toString() function?  Does the compiler let you call toString() explicitly on the instances of that class?  In es3.js, toString() has been declared for Array, Date, etc.  I want to make sure it behaves the way we want for other classes that may not have declared a toString().

**Comment by adufilie** [comment]
ActionScript gives an error if you try to use toString() on a non-dynamic class that does not define it explicitly.  Is there a reason we should make it behave differently when using js.swc, considering that all the extern files define toString()?

**Comment by aharui** [comment]
No, we just want to make sure we have the same behavior that AS coders expect.  I'll try to apply the correct set of your patches and see what happens.

**Comment by aharui** [comment]
Still not working.  Maybe the patches didn't applied correctly, but createjs.Text.toString() is still being generated even though there is a createjs.DisplayObject.toString()

**Comment by adufilie** [comment]
At one point I had it working, but you're right, it currently isn't.  I must've been modifying the wrong set of files when I was testing overriding toString().  Here's what I'm seeing now:
When creating a new class Test1, you can and define toString() however you want.  When you create Test2 extending Test1, you need to specify the override keyword.

The code is using multiple ways to determine whether or not a method is an override:
* getClassReference().hasSuperMethod(qName)
* getComment().isOverride()
* getClassReference().getMethodOverrideFromInterface(this)

**Comment by adufilie** [comment]
Ok, I've reworked and updated the patch. I managed to move all the toString-related special-case code into a single if statement. Please try again.

**Comment by adufilie** [comment]
The one piece I didn't realize before was that since these classes are serving the purpose of an external interface, subclasses need not include override methods since they must have the same signature as the super methods anyway.  toString() is now absent from Object, present in EventDispatcher and Number, and absent from subclasses of EventDispatcher such as Text and DisplayObject.

**Comment by aharui** [comment]
Yes, there some subtle things to the extern compiler.  Thanks for sticking with it.  Everything passes for me and I pushed it to the repo.

**Comment by aharui** [comment]
I think the github integration scripts didn't quite work.  Can you manually close the pull request?

**Comment by Harbs** [comment]
In my experience, there's two ways to automatically close the pull request:
1. including a comment: "This closes #5". (or whatever the pull request number is) when applying the patch.
2. Using the command line to merge the pull request directly.
The advantage of the second approach is that the commit keeps the contributor's name.

**Comment by adufilie** [comment]
The patch didn't apply correctly. Commits were included that should have been replaced. I've created a new pull request to revert the bad commits and re-apply this patch.

**Comment by aharui** [comment]
@Harbs: Yes, that has been working for me, but for some reason, when I pulled the last set of changes there was a merge conflict and after resolving them, the system didn't close the PR.  Maybe I've been merging these changes incorrectly.  I just keep running git pull without reverting back to before the commits.   I could make a fake commit, but it seems better for Andy to just manually close this one.

**Comment by adufilie** [comment]
I noticed that there was no merge commit after applying the patch. On the "Git for Apache Flex Guide" (https://cwiki.apache.org/confluence/display/FLEX/Git+for+Apache+Flex+Guide) it links to a description of your branching model (http://nvie.com/posts/a-successful-git-branching-model/) which suggests using "git merge --no-ff" to preserve the merge history and make it easier to roll back.  "git pull --no-ff" would also work, but revert is needed if you do it multiple times.

**Comment by adufilie** [comment]
Sorry, I meant "git reset", not revert.

**Pull request closed without merging**
